### ISSUE TITLE
hello when u will add download by playlist

### ISSUE THREAD

**Issue by hadoizz** [SazumiVicky/spotify-dl#1]
hey hope u doing well i like what u doing but why u dont add playlist downlaodier also

**Comment by SazumiVicky** [comment]
Hi! Thanks for your kind words and feedback. I appreciate your suggestion about adding a playlist downloader.

Currently, I may not have implemented that feature due to either technical complexity, time limitations, or to keep the tool simple. However, I'll definitely consider it for future updates! If you have any specific ideas or want to contribute, feel free to submit a pull request or share more details.

Thanks again for your support!
